module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
    project: './tsconfig.json',
  },
  plugins: ['prettier', 'import', 'jest', '@typescript-eslint'],
  env: {
    'jest/globals': true,
    node: true,
    es6: true,
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
  rules: {
    quotes: [
      'error',
      'single',
      {
        avoidEscape: true,
      },
    ],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'never',
      },
    ],
    curly: ['error'],
    'object-curly-newline': ['off'],
    'object-shorthand': ['error'],
    'no-confusing-arrow': ['off'],
    'sort-imports': [
      'error',
      {
        ignoreDeclarationSort: true,
        ignoreCase: false,
        ignoreMemberSort: false,
        allowSeparatedGroups: false,
      },
    ],
    'import/order': [
      'error',
      {
        alphabetize: {
          order: 'asc',
          caseInsensitive: false,
        },
        'newlines-between': 'always',
        groups: ['builtin', 'external', ['sibling', 'parent'], 'index'],
        warnOnUnassignedImports: false,
      },
    ],
    'import/prefer-default-export': ['off'],
    'no-console': ['off'],
    'no-unused-expressions': ['off'],
    'no-unused-vars': ['off'],
    'no-nested-ternary': ['error'],
    '@typescript-eslint/no-unused-vars': ['error'],
    '@typescript-eslint/no-explicit-any': ['off'],
    'no-undef': ['error'],
    'arrow-parens': ['off'],
    'arrow-body-style': ['error', 'as-needed'],
    'function-paren-newline': ['off'],
    indent: ['off'],
    'no-mixed-operators': ['off'],
    'no-plusplus': ['off'],
    'import/named': ['error'],
    'import/no-unresolved': ['error'],
    'import/default': ['error'],
    'prettier/prettier': ['error'],
    'global-require': ['off'],
    'prefer-template': ['error'],
    'import/no-extraneous-dependencies': ['error'],
    'jest/no-disabled-tests': ['warn'],
    'jest/no-focused-tests': ['error'],
    'jest/no-identical-title': ['error'],
    'jest/prefer-to-have-length': ['warn'],
    'jest/valid-expect': ['error'],
    '@typescript-eslint/adjacent-overload-signatures': ['error'],
    '@typescript-eslint/ban-ts-comment': ['error'],
    '@typescript-eslint/ban-types': ['error'],
    'no-array-constructor': ['off'],
    '@typescript-eslint/no-array-constructor': ['error'],
    'no-empty-function': ['off'],
    '@typescript-eslint/no-empty-function': ['error'],
    '@typescript-eslint/no-empty-interface': ['error'],
    '@typescript-eslint/no-extra-non-null-assertion': ['error'],
    'no-extra-semi': ['off'],
    '@typescript-eslint/no-extra-semi': ['error'],
    '@typescript-eslint/no-inferrable-types': ['error'],
    'no-loss-of-precision': ['off'],
    '@typescript-eslint/no-loss-of-precision': ['error'],
    '@typescript-eslint/no-misused-new': ['error'],
    '@typescript-eslint/no-namespace': ['error'],
    '@typescript-eslint/no-non-null-asserted-optional-chain': ['error'],
    '@typescript-eslint/no-non-null-assertion': ['warn'],
    '@typescript-eslint/no-this-alias': ['error'],
    '@typescript-eslint/no-unnecessary-type-constraint': ['error'],
    '@typescript-eslint/no-var-requires': ['error'],
    '@typescript-eslint/prefer-as-const': ['error'],
    '@typescript-eslint/prefer-namespace-keyword': ['error'],
    '@typescript-eslint/triple-slash-reference': ['error'],
    'constructor-super': ['off'],
    'getter-return': ['off'],
    'no-const-assign': ['off'],
    'no-dupe-args': ['off'],
    'no-dupe-class-members': ['off'],
    'no-dupe-keys': ['off'],
    'no-func-assign': ['off'],
    'no-import-assign': ['off'],
    'no-new-symbol': ['off'],
    'no-obj-calls': ['off'],
    'no-redeclare': ['off'],
    'no-setter-return': ['off'],
    'no-this-before-super': ['off'],
    'no-unreachable': ['off'],
    'no-unsafe-negation': ['off'],
    'no-var': ['error'],
    'prefer-const': ['error'],
    'prefer-rest-params': ['error'],
    'prefer-spread': ['error'],
    'valid-typeof': ['off'],
    'prefer-arrow-callback': ['off'],
    'lines-around-comment': [0],
    'max-len': [0],
    'no-tabs': [0],
    'no-unexpected-multiline': [0],
    '@typescript-eslint/quotes': [0],
    'babel/quotes': [0],
    'array-bracket-newline': ['off'],
    'array-bracket-spacing': ['off'],
    'array-element-newline': ['off'],
    'arrow-spacing': ['off'],
    'block-spacing': ['off'],
    'brace-style': ['off'],
    'comma-spacing': ['off'],
    'comma-style': ['off'],
    'computed-property-spacing': ['off'],
    'dot-location': ['off'],
    'eol-last': ['off'],
    'func-call-spacing': ['off'],
    'function-call-argument-newline': ['off'],
    'generator-star': ['off'],
    'generator-star-spacing': ['off'],
    'implicit-arrow-linebreak': ['off'],
    'jsx-quotes': ['off'],
    'key-spacing': ['off'],
    'keyword-spacing': ['off'],
    'linebreak-style': ['off'],
    'multiline-ternary': ['off'],
    'newline-per-chained-call': ['off'],
    'new-parens': ['off'],
    'no-arrow-condition': ['off'],
    'no-comma-dangle': ['off'],
    'no-extra-parens': ['off'],
    'no-floating-decimal': ['off'],
    'no-mixed-spaces-and-tabs': ['off'],
    'no-multi-spaces': ['off'],
    'no-multiple-empty-lines': ['off'],
    'no-reserved-keys': ['off'],
    'no-space-before-semi': ['off'],
    'no-trailing-spaces': ['off'],
    'no-whitespace-before-property': ['off'],
    'no-wrap-func': ['off'],
    'nonblock-statement-body-position': ['off'],
    'object-curly-spacing': ['off'],
    'object-property-newline': ['off'],
    'one-var-declaration-per-line': ['off'],
    'operator-linebreak': ['off'],
    'padded-blocks': ['off'],
    'quote-props': ['off'],
    'rest-spread-spacing': ['off'],
    semi: ['off'],
    'semi-spacing': ['off'],
    'semi-style': ['off'],
    'space-after-function-name': ['off'],
    'space-after-keywords': ['off'],
    'space-before-blocks': ['off'],
    'space-before-function-paren': ['off'],
    'space-before-function-parentheses': ['off'],
    'space-before-keywords': ['off'],
    'space-in-brackets': ['off'],
    'space-in-parens': ['off'],
    'space-infix-ops': ['off'],
    'space-return-throw-case': ['off'],
    'space-unary-ops': ['off'],
    'space-unary-word-ops': ['off'],
    'switch-colon-spacing': ['off'],
    'template-curly-spacing': ['off'],
    'template-tag-spacing': ['off'],
    'unicode-bom': ['off'],
    'wrap-iife': ['off'],
    'wrap-regex': ['off'],
    'yield-star-spacing': ['off'],
    '@babel/object-curly-spacing': ['off'],
    '@babel/semi': ['off'],
    '@typescript-eslint/brace-style': ['off'],
    '@typescript-eslint/comma-dangle': ['off'],
    '@typescript-eslint/comma-spacing': ['off'],
    '@typescript-eslint/func-call-spacing': ['off'],
    '@typescript-eslint/indent': ['off'],
    '@typescript-eslint/keyword-spacing': ['off'],
    '@typescript-eslint/member-delimiter-style': ['off'],
    '@typescript-eslint/no-extra-parens': ['off'],
    '@typescript-eslint/object-curly-spacing': ['off'],
    '@typescript-eslint/semi': ['off'],
    '@typescript-eslint/space-before-blocks': ['off'],
    '@typescript-eslint/space-before-function-paren': ['off'],
    '@typescript-eslint/space-infix-ops': ['off'],
    '@typescript-eslint/type-annotation-spacing': ['off'],
    'babel/object-curly-spacing': ['off'],
    'babel/semi': ['off'],
    'flowtype/boolean-style': ['off'],
    'flowtype/delimiter-dangle': ['off'],
    'flowtype/generic-spacing': ['off'],
    'flowtype/object-type-curly-spacing': ['off'],
    'flowtype/object-type-delimiter': ['off'],
    'flowtype/quotes': ['off'],
    'flowtype/semi': ['off'],
    'flowtype/space-after-type-colon': ['off'],
    'flowtype/space-before-generic-bracket': ['off'],
    'flowtype/space-before-type-colon': ['off'],
    'flowtype/union-intersection-spacing': ['off'],
    'standard/array-bracket-even-spacing': ['off'],
    'standard/computed-property-even-spacing': ['off'],
    'standard/object-curly-even-spacing': ['off'],
    'unicorn/empty-brace-spaces': ['off'],
    'unicorn/no-nested-ternary': ['off'],
    'unicorn/number-literal-case': ['off'],
    'indent-legacy': ['off'],
    'no-spaced-func': ['off'],
  },
  ignorePatterns: [
    'babel.config.js',
    'jestConfig.js',
    'node_modules',
    '.webpack',
  ],
};
